// This file is generated by rust-protobuf 3.2.0. Do not edit
// .proto file is parsed by protoc 3.12.4
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `gz/msgs/twist_with_covariance.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_2_0;

#[derive(PartialEq,Clone,Default,Debug)]
// @@protoc_insertion_point(message:gz.msgs.TwistWithCovariance)
pub struct TwistWithCovariance {
    // message fields
    // @@protoc_insertion_point(field:gz.msgs.TwistWithCovariance.twist)
    pub twist: ::protobuf::MessageField<super::twist::Twist>,
    // @@protoc_insertion_point(field:gz.msgs.TwistWithCovariance.covariance)
    pub covariance: ::protobuf::MessageField<super::float_v::Float_V>,
    // special fields
    // @@protoc_insertion_point(special_field:gz.msgs.TwistWithCovariance.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a TwistWithCovariance {
    fn default() -> &'a TwistWithCovariance {
        <TwistWithCovariance as ::protobuf::Message>::default_instance()
    }
}

impl TwistWithCovariance {
    pub fn new() -> TwistWithCovariance {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::twist::Twist>(
            "twist",
            |m: &TwistWithCovariance| { &m.twist },
            |m: &mut TwistWithCovariance| { &mut m.twist },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::float_v::Float_V>(
            "covariance",
            |m: &TwistWithCovariance| { &m.covariance },
            |m: &mut TwistWithCovariance| { &mut m.covariance },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<TwistWithCovariance>(
            "TwistWithCovariance",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for TwistWithCovariance {
    const NAME: &'static str = "TwistWithCovariance";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.twist)?;
                },
                18 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.covariance)?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.twist.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.covariance.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.twist.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
        }
        if let Some(v) = self.covariance.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> TwistWithCovariance {
        TwistWithCovariance::new()
    }

    fn clear(&mut self) {
        self.twist.clear();
        self.covariance.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static TwistWithCovariance {
        static instance: TwistWithCovariance = TwistWithCovariance {
            twist: ::protobuf::MessageField::none(),
            covariance: ::protobuf::MessageField::none(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for TwistWithCovariance {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("TwistWithCovariance").unwrap()).clone()
    }
}

impl ::std::fmt::Display for TwistWithCovariance {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for TwistWithCovariance {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n#gz/msgs/twist_with_covariance.proto\x12\x07gz.msgs\x1a\x15gz/msgs/flo\
    at_v.proto\x1a\x13gz/msgs/twist.proto\"m\n\x13TwistWithCovariance\x12$\n\
    \x05twist\x18\x01\x20\x01(\x0b2\x0e.gz.msgs.TwistR\x05twist\x120\n\ncova\
    riance\x18\x02\x20\x01(\x0b2\x10.gz.msgs.Float_VR\ncovarianceB(\n\x0bcom\
    .gz.msgsB\x19TwistWithCovarianceProtosb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(2);
            deps.push(super::float_v::file_descriptor().clone());
            deps.push(super::twist::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(TwistWithCovariance::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
