// This file is generated by rust-protobuf 3.7.2. Do not edit
// .proto file is parsed by protoc 3.21.12
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `gz/msgs/pid.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_2;

#[derive(::gz_msgs_common::GzMessage)]
// @@protoc_insertion_point(message:gz.msgs.PID)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct PID {
    // message fields
    // @@protoc_insertion_point(field:gz.msgs.PID.header)
    pub header: ::protobuf::MessageField<super::header::Header>,
    // @@protoc_insertion_point(field:gz.msgs.PID.target_optional)
    pub target_optional: ::protobuf::MessageField<super::double::Double>,
    // @@protoc_insertion_point(field:gz.msgs.PID.p_gain_optional)
    pub p_gain_optional: ::protobuf::MessageField<super::double::Double>,
    // @@protoc_insertion_point(field:gz.msgs.PID.i_gain_optional)
    pub i_gain_optional: ::protobuf::MessageField<super::double::Double>,
    // @@protoc_insertion_point(field:gz.msgs.PID.d_gain_optional)
    pub d_gain_optional: ::protobuf::MessageField<super::double::Double>,
    // @@protoc_insertion_point(field:gz.msgs.PID.i_max_optional)
    pub i_max_optional: ::protobuf::MessageField<super::double::Double>,
    // @@protoc_insertion_point(field:gz.msgs.PID.i_min_optional)
    pub i_min_optional: ::protobuf::MessageField<super::double::Double>,
    // @@protoc_insertion_point(field:gz.msgs.PID.limit_optional)
    pub limit_optional: ::protobuf::MessageField<super::double::Double>,
    // special fields
    // @@protoc_insertion_point(special_field:gz.msgs.PID.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a PID {
    fn default() -> &'a PID {
        <PID as ::protobuf::Message>::default_instance()
    }
}

impl PID {
    pub fn new() -> PID {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(8);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::header::Header>(
            "header",
            |m: &PID| { &m.header },
            |m: &mut PID| { &mut m.header },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::double::Double>(
            "target_optional",
            |m: &PID| { &m.target_optional },
            |m: &mut PID| { &mut m.target_optional },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::double::Double>(
            "p_gain_optional",
            |m: &PID| { &m.p_gain_optional },
            |m: &mut PID| { &mut m.p_gain_optional },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::double::Double>(
            "i_gain_optional",
            |m: &PID| { &m.i_gain_optional },
            |m: &mut PID| { &mut m.i_gain_optional },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::double::Double>(
            "d_gain_optional",
            |m: &PID| { &m.d_gain_optional },
            |m: &mut PID| { &mut m.d_gain_optional },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::double::Double>(
            "i_max_optional",
            |m: &PID| { &m.i_max_optional },
            |m: &mut PID| { &mut m.i_max_optional },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::double::Double>(
            "i_min_optional",
            |m: &PID| { &m.i_min_optional },
            |m: &mut PID| { &mut m.i_min_optional },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::double::Double>(
            "limit_optional",
            |m: &PID| { &m.limit_optional },
            |m: &mut PID| { &mut m.limit_optional },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<PID>(
            "PID",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for PID {
    const NAME: &'static str = "PID";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.header)?;
                },
                18 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.target_optional)?;
                },
                26 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.p_gain_optional)?;
                },
                34 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.i_gain_optional)?;
                },
                42 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.d_gain_optional)?;
                },
                50 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.i_max_optional)?;
                },
                58 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.i_min_optional)?;
                },
                66 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.limit_optional)?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.header.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.target_optional.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.p_gain_optional.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.i_gain_optional.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.d_gain_optional.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.i_max_optional.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.i_min_optional.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.limit_optional.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.header.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
        }
        if let Some(v) = self.target_optional.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
        }
        if let Some(v) = self.p_gain_optional.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(3, v, os)?;
        }
        if let Some(v) = self.i_gain_optional.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(4, v, os)?;
        }
        if let Some(v) = self.d_gain_optional.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(5, v, os)?;
        }
        if let Some(v) = self.i_max_optional.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(6, v, os)?;
        }
        if let Some(v) = self.i_min_optional.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(7, v, os)?;
        }
        if let Some(v) = self.limit_optional.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(8, v, os)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> PID {
        PID::new()
    }

    fn clear(&mut self) {
        self.header.clear();
        self.target_optional.clear();
        self.p_gain_optional.clear();
        self.i_gain_optional.clear();
        self.d_gain_optional.clear();
        self.i_max_optional.clear();
        self.i_min_optional.clear();
        self.limit_optional.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static PID {
        static instance: PID = PID {
            header: ::protobuf::MessageField::none(),
            target_optional: ::protobuf::MessageField::none(),
            p_gain_optional: ::protobuf::MessageField::none(),
            i_gain_optional: ::protobuf::MessageField::none(),
            d_gain_optional: ::protobuf::MessageField::none(),
            i_max_optional: ::protobuf::MessageField::none(),
            i_min_optional: ::protobuf::MessageField::none(),
            limit_optional: ::protobuf::MessageField::none(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for PID {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("PID").unwrap()).clone()
    }
}

impl ::std::fmt::Display for PID {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for PID {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x11gz/msgs/pid.proto\x12\x07gz.msgs\x1a\x14gz/msgs/double.proto\x1a\
    \x14gz/msgs/header.proto\"\xb9\x03\n\x03PID\x12'\n\x06header\x18\x01\x20\
    \x01(\x0b2\x0f.gz.msgs.HeaderR\x06header\x128\n\x0ftarget_optional\x18\
    \x02\x20\x01(\x0b2\x0f.gz.msgs.DoubleR\x0etargetOptional\x127\n\x0fp_gai\
    n_optional\x18\x03\x20\x01(\x0b2\x0f.gz.msgs.DoubleR\rpGainOptional\x127\
    \n\x0fi_gain_optional\x18\x04\x20\x01(\x0b2\x0f.gz.msgs.DoubleR\riGainOp\
    tional\x127\n\x0fd_gain_optional\x18\x05\x20\x01(\x0b2\x0f.gz.msgs.Doubl\
    eR\rdGainOptional\x125\n\x0ei_max_optional\x18\x06\x20\x01(\x0b2\x0f.gz.\
    msgs.DoubleR\x0ciMaxOptional\x125\n\x0ei_min_optional\x18\x07\x20\x01(\
    \x0b2\x0f.gz.msgs.DoubleR\x0ciMinOptional\x126\n\x0elimit_optional\x18\
    \x08\x20\x01(\x0b2\x0f.gz.msgs.DoubleR\rlimitOptionalB\x18\n\x0bcom.gz.m\
    sgsB\tPIDProtosb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(2);
            deps.push(super::double::file_descriptor().clone());
            deps.push(super::header::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(PID::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
