[package]
name = "gz-msgs-build"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
protobuf.workspace = true
protobuf-codegen = "3"
