// This file is generated by rust-protobuf 3.7.2. Do not edit
// .proto file is parsed by protoc 3.21.12
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `ignition/msgs/gps_sensor.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_2;

#[derive(::gz_msgs_common::IgnMessage)]
// @@protoc_insertion_point(message:ignition.msgs.GPSSensor)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct GPSSensor {
    // message fields
    // @@protoc_insertion_point(field:ignition.msgs.GPSSensor.header)
    pub header: ::protobuf::MessageField<super::header::Header>,
    // @@protoc_insertion_point(field:ignition.msgs.GPSSensor.position)
    pub position: ::protobuf::MessageField<gpssensor::Sensing>,
    // @@protoc_insertion_point(field:ignition.msgs.GPSSensor.velocity)
    pub velocity: ::protobuf::MessageField<gpssensor::Sensing>,
    // special fields
    // @@protoc_insertion_point(special_field:ignition.msgs.GPSSensor.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a GPSSensor {
    fn default() -> &'a GPSSensor {
        <GPSSensor as ::protobuf::Message>::default_instance()
    }
}

impl GPSSensor {
    pub fn new() -> GPSSensor {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(3);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::header::Header>(
            "header",
            |m: &GPSSensor| { &m.header },
            |m: &mut GPSSensor| { &mut m.header },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, gpssensor::Sensing>(
            "position",
            |m: &GPSSensor| { &m.position },
            |m: &mut GPSSensor| { &mut m.position },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, gpssensor::Sensing>(
            "velocity",
            |m: &GPSSensor| { &m.velocity },
            |m: &mut GPSSensor| { &mut m.velocity },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<GPSSensor>(
            "GPSSensor",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for GPSSensor {
    const NAME: &'static str = "GPSSensor";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.header)?;
                },
                18 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.position)?;
                },
                26 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.velocity)?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.header.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.position.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.velocity.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.header.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
        }
        if let Some(v) = self.position.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
        }
        if let Some(v) = self.velocity.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(3, v, os)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> GPSSensor {
        GPSSensor::new()
    }

    fn clear(&mut self) {
        self.header.clear();
        self.position.clear();
        self.velocity.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static GPSSensor {
        static instance: GPSSensor = GPSSensor {
            header: ::protobuf::MessageField::none(),
            position: ::protobuf::MessageField::none(),
            velocity: ::protobuf::MessageField::none(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for GPSSensor {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("GPSSensor").unwrap()).clone()
    }
}

impl ::std::fmt::Display for GPSSensor {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for GPSSensor {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

/// Nested message and enums of message `GPSSensor`
pub mod gpssensor {
    #[derive(::gz_msgs_common::IgnMessage)]
    // @@protoc_insertion_point(message:ignition.msgs.GPSSensor.Sensing)
    #[derive(PartialEq,Clone,Default,Debug)]
    pub struct Sensing {
        // message fields
        // @@protoc_insertion_point(field:ignition.msgs.GPSSensor.Sensing.horizontal_noise)
        pub horizontal_noise: ::protobuf::MessageField<super::super::sensor_noise::SensorNoise>,
        // @@protoc_insertion_point(field:ignition.msgs.GPSSensor.Sensing.vertical_noise)
        pub vertical_noise: ::protobuf::MessageField<super::super::sensor_noise::SensorNoise>,
        // special fields
        // @@protoc_insertion_point(special_field:ignition.msgs.GPSSensor.Sensing.special_fields)
        pub special_fields: ::protobuf::SpecialFields,
    }

    impl<'a> ::std::default::Default for &'a Sensing {
        fn default() -> &'a Sensing {
            <Sensing as ::protobuf::Message>::default_instance()
        }
    }

    impl Sensing {
        pub fn new() -> Sensing {
            ::std::default::Default::default()
        }

        pub(in super) fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
            let mut fields = ::std::vec::Vec::with_capacity(2);
            let mut oneofs = ::std::vec::Vec::with_capacity(0);
            fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::super::sensor_noise::SensorNoise>(
                "horizontal_noise",
                |m: &Sensing| { &m.horizontal_noise },
                |m: &mut Sensing| { &mut m.horizontal_noise },
            ));
            fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::super::sensor_noise::SensorNoise>(
                "vertical_noise",
                |m: &Sensing| { &m.vertical_noise },
                |m: &mut Sensing| { &mut m.vertical_noise },
            ));
            ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<Sensing>(
                "GPSSensor.Sensing",
                fields,
                oneofs,
            )
        }
    }

    impl ::protobuf::Message for Sensing {
        const NAME: &'static str = "Sensing";

        fn is_initialized(&self) -> bool {
            true
        }

        fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
            while let Some(tag) = is.read_raw_tag_or_eof()? {
                match tag {
                    10 => {
                        ::protobuf::rt::read_singular_message_into_field(is, &mut self.horizontal_noise)?;
                    },
                    18 => {
                        ::protobuf::rt::read_singular_message_into_field(is, &mut self.vertical_noise)?;
                    },
                    tag => {
                        ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                    },
                };
            }
            ::std::result::Result::Ok(())
        }

        // Compute sizes of nested messages
        #[allow(unused_variables)]
        fn compute_size(&self) -> u64 {
            let mut my_size = 0;
            if let Some(v) = self.horizontal_noise.as_ref() {
                let len = v.compute_size();
                my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
            }
            if let Some(v) = self.vertical_noise.as_ref() {
                let len = v.compute_size();
                my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
            }
            my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
            self.special_fields.cached_size().set(my_size as u32);
            my_size
        }

        fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
            if let Some(v) = self.horizontal_noise.as_ref() {
                ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
            }
            if let Some(v) = self.vertical_noise.as_ref() {
                ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
            }
            os.write_unknown_fields(self.special_fields.unknown_fields())?;
            ::std::result::Result::Ok(())
        }

        fn special_fields(&self) -> &::protobuf::SpecialFields {
            &self.special_fields
        }

        fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
            &mut self.special_fields
        }

        fn new() -> Sensing {
            Sensing::new()
        }

        fn clear(&mut self) {
            self.horizontal_noise.clear();
            self.vertical_noise.clear();
            self.special_fields.clear();
        }

        fn default_instance() -> &'static Sensing {
            static instance: Sensing = Sensing {
                horizontal_noise: ::protobuf::MessageField::none(),
                vertical_noise: ::protobuf::MessageField::none(),
                special_fields: ::protobuf::SpecialFields::new(),
            };
            &instance
        }
    }

    impl ::protobuf::MessageFull for Sensing {
        fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
            static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
            descriptor.get(|| super::file_descriptor().message_by_package_relative_name("GPSSensor.Sensing").unwrap()).clone()
        }
    }

    impl ::std::fmt::Display for Sensing {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            ::protobuf::text_format::fmt(self, f)
        }
    }

    impl ::protobuf::reflect::ProtobufValue for Sensing {
        type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x1eignition/msgs/gps_sensor.proto\x12\rignition.msgs\x1a\x20ignition/\
    msgs/sensor_noise.proto\x1a\x1aignition/msgs/header.proto\"\xcc\x02\n\tG\
    PSSensor\x12-\n\x06header\x18\x01\x20\x01(\x0b2\x15.ignition.msgs.Header\
    R\x06header\x12<\n\x08position\x18\x02\x20\x01(\x0b2\x20.ignition.msgs.G\
    PSSensor.SensingR\x08position\x12<\n\x08velocity\x18\x03\x20\x01(\x0b2\
    \x20.ignition.msgs.GPSSensor.SensingR\x08velocity\x1a\x93\x01\n\x07Sensi\
    ng\x12E\n\x10horizontal_noise\x18\x01\x20\x01(\x0b2\x1a.ignition.msgs.Se\
    nsorNoiseR\x0fhorizontalNoise\x12A\n\x0evertical_noise\x18\x02\x20\x01(\
    \x0b2\x1a.ignition.msgs.SensorNoiseR\rverticalNoiseB\x1b\n\x11com.igniti\
    on.msgsB\x06Protosb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(2);
            deps.push(super::sensor_noise::file_descriptor().clone());
            deps.push(super::header::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(2);
            messages.push(GPSSensor::generated_message_descriptor_data());
            messages.push(gpssensor::Sensing::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
