[package]
name = "gz-msgs"
version = "0.4.0"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true
description = "Rust implmentation of Gazebo Messages"
readme = "README.md"
keywords = ["gazebo", "robotics", "simulation", "messages"]
categories = ["data-strctures"]
include = ["Cargo.toml", "src/**/*.rs", "build.rs", "3rdparty/**/*.proto"]

[dependencies]
protobuf = "3"
gz-msgs-derive.workspace = true

[build-dependencies]
protobuf = "3"
protobuf-codegen = "3"

[features]
ignition = []
