// This file is generated by rust-protobuf 3.3.0. Do not edit
// .proto file is parsed by protoc 3.12.4
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `gz/msgs/atmosphere.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_3_0;

#[derive(::gz_msgs_common::GzMessage)]
// @@protoc_insertion_point(message:gz.msgs.Atmosphere)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct Atmosphere {
    // message fields
    // @@protoc_insertion_point(field:gz.msgs.Atmosphere.header)
    pub header: ::protobuf::MessageField<super::header::Header>,
    // @@protoc_insertion_point(field:gz.msgs.Atmosphere.type)
    pub type_: ::protobuf::EnumOrUnknown<atmosphere::Type>,
    // @@protoc_insertion_point(field:gz.msgs.Atmosphere.temperature)
    pub temperature: f64,
    // @@protoc_insertion_point(field:gz.msgs.Atmosphere.pressure)
    pub pressure: f64,
    // @@protoc_insertion_point(field:gz.msgs.Atmosphere.mass_density)
    pub mass_density: f64,
    // @@protoc_insertion_point(field:gz.msgs.Atmosphere.enable_atmosphere)
    pub enable_atmosphere: bool,
    // special fields
    // @@protoc_insertion_point(special_field:gz.msgs.Atmosphere.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a Atmosphere {
    fn default() -> &'a Atmosphere {
        <Atmosphere as ::protobuf::Message>::default_instance()
    }
}

impl Atmosphere {
    pub fn new() -> Atmosphere {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(6);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::header::Header>(
            "header",
            |m: &Atmosphere| { &m.header },
            |m: &mut Atmosphere| { &mut m.header },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "type",
            |m: &Atmosphere| { &m.type_ },
            |m: &mut Atmosphere| { &mut m.type_ },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "temperature",
            |m: &Atmosphere| { &m.temperature },
            |m: &mut Atmosphere| { &mut m.temperature },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "pressure",
            |m: &Atmosphere| { &m.pressure },
            |m: &mut Atmosphere| { &mut m.pressure },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "mass_density",
            |m: &Atmosphere| { &m.mass_density },
            |m: &mut Atmosphere| { &mut m.mass_density },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "enable_atmosphere",
            |m: &Atmosphere| { &m.enable_atmosphere },
            |m: &mut Atmosphere| { &mut m.enable_atmosphere },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<Atmosphere>(
            "Atmosphere",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for Atmosphere {
    const NAME: &'static str = "Atmosphere";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.header)?;
                },
                16 => {
                    self.type_ = is.read_enum_or_unknown()?;
                },
                25 => {
                    self.temperature = is.read_double()?;
                },
                33 => {
                    self.pressure = is.read_double()?;
                },
                41 => {
                    self.mass_density = is.read_double()?;
                },
                48 => {
                    self.enable_atmosphere = is.read_bool()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.header.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if self.type_ != ::protobuf::EnumOrUnknown::new(atmosphere::Type::ADIABATIC) {
            my_size += ::protobuf::rt::int32_size(2, self.type_.value());
        }
        if self.temperature != 0. {
            my_size += 1 + 8;
        }
        if self.pressure != 0. {
            my_size += 1 + 8;
        }
        if self.mass_density != 0. {
            my_size += 1 + 8;
        }
        if self.enable_atmosphere != false {
            my_size += 1 + 1;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.header.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
        }
        if self.type_ != ::protobuf::EnumOrUnknown::new(atmosphere::Type::ADIABATIC) {
            os.write_enum(2, ::protobuf::EnumOrUnknown::value(&self.type_))?;
        }
        if self.temperature != 0. {
            os.write_double(3, self.temperature)?;
        }
        if self.pressure != 0. {
            os.write_double(4, self.pressure)?;
        }
        if self.mass_density != 0. {
            os.write_double(5, self.mass_density)?;
        }
        if self.enable_atmosphere != false {
            os.write_bool(6, self.enable_atmosphere)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> Atmosphere {
        Atmosphere::new()
    }

    fn clear(&mut self) {
        self.header.clear();
        self.type_ = ::protobuf::EnumOrUnknown::new(atmosphere::Type::ADIABATIC);
        self.temperature = 0.;
        self.pressure = 0.;
        self.mass_density = 0.;
        self.enable_atmosphere = false;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static Atmosphere {
        static instance: Atmosphere = Atmosphere {
            header: ::protobuf::MessageField::none(),
            type_: ::protobuf::EnumOrUnknown::from_i32(0),
            temperature: 0.,
            pressure: 0.,
            mass_density: 0.,
            enable_atmosphere: false,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for Atmosphere {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("Atmosphere").unwrap()).clone()
    }
}

impl ::std::fmt::Display for Atmosphere {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Atmosphere {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

/// Nested message and enums of message `Atmosphere`
pub mod atmosphere {
    #[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
    // @@protoc_insertion_point(enum:gz.msgs.Atmosphere.Type)
    pub enum Type {
        // @@protoc_insertion_point(enum_value:gz.msgs.Atmosphere.Type.ADIABATIC)
        ADIABATIC = 0,
    }

    impl ::protobuf::Enum for Type {
        const NAME: &'static str = "Type";

        fn value(&self) -> i32 {
            *self as i32
        }

        fn from_i32(value: i32) -> ::std::option::Option<Type> {
            match value {
                0 => ::std::option::Option::Some(Type::ADIABATIC),
                _ => ::std::option::Option::None
            }
        }

        fn from_str(str: &str) -> ::std::option::Option<Type> {
            match str {
                "ADIABATIC" => ::std::option::Option::Some(Type::ADIABATIC),
                _ => ::std::option::Option::None
            }
        }

        const VALUES: &'static [Type] = &[
            Type::ADIABATIC,
        ];
    }

    impl ::protobuf::EnumFull for Type {
        fn enum_descriptor() -> ::protobuf::reflect::EnumDescriptor {
            static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::Lazy::new();
            descriptor.get(|| super::file_descriptor().enum_by_package_relative_name("Atmosphere.Type").unwrap()).clone()
        }

        fn descriptor(&self) -> ::protobuf::reflect::EnumValueDescriptor {
            let index = *self as usize;
            Self::enum_descriptor().value_by_index(index)
        }
    }

    impl ::std::default::Default for Type {
        fn default() -> Self {
            Type::ADIABATIC
        }
    }

    impl Type {
        pub(in super) fn generated_enum_descriptor_data() -> ::protobuf::reflect::GeneratedEnumDescriptorData {
            ::protobuf::reflect::GeneratedEnumDescriptorData::new::<Type>("Atmosphere.Type")
        }
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x18gz/msgs/atmosphere.proto\x12\x07gz.msgs\x1a\x14gz/msgs/header.prot\
    o\"\x88\x02\n\nAtmosphere\x12'\n\x06header\x18\x01\x20\x01(\x0b2\x0f.gz.\
    msgs.HeaderR\x06header\x12,\n\x04type\x18\x02\x20\x01(\x0e2\x18.gz.msgs.\
    Atmosphere.TypeR\x04type\x12\x20\n\x0btemperature\x18\x03\x20\x01(\x01R\
    \x0btemperature\x12\x1a\n\x08pressure\x18\x04\x20\x01(\x01R\x08pressure\
    \x12!\n\x0cmass_density\x18\x05\x20\x01(\x01R\x0bmassDensity\x12+\n\x11e\
    nable_atmosphere\x18\x06\x20\x01(\x08R\x10enableAtmosphere\"\x15\n\x04Ty\
    pe\x12\r\n\tADIABATIC\x10\0B\x1f\n\x0bcom.gz.msgsB\x10AtmosphereProtosb\
    \x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(1);
            deps.push(super::header::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(Atmosphere::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(1);
            enums.push(atmosphere::Type::generated_enum_descriptor_data());
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
