// This file is generated by rust-protobuf 3.2.0. Do not edit
// .proto file is parsed by protoc 3.12.4
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `ignition/msgs/world_reset.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_2_0;

#[derive(PartialEq,Clone,Default,Debug)]
#[derive(::gz_msgs_derive::IgnMessage)]
// @@protoc_insertion_point(message:ignition.msgs.WorldReset)
pub struct WorldReset {
    // message fields
    // @@protoc_insertion_point(field:ignition.msgs.WorldReset.header)
    pub header: ::protobuf::MessageField<super::header::Header>,
    // @@protoc_insertion_point(field:ignition.msgs.WorldReset.all)
    pub all: bool,
    // @@protoc_insertion_point(field:ignition.msgs.WorldReset.time_only)
    pub time_only: bool,
    // @@protoc_insertion_point(field:ignition.msgs.WorldReset.model_only)
    pub model_only: bool,
    // special fields
    // @@protoc_insertion_point(special_field:ignition.msgs.WorldReset.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a WorldReset {
    fn default() -> &'a WorldReset {
        <WorldReset as ::protobuf::Message>::default_instance()
    }
}

impl WorldReset {
    pub fn new() -> WorldReset {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(4);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::header::Header>(
            "header",
            |m: &WorldReset| { &m.header },
            |m: &mut WorldReset| { &mut m.header },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "all",
            |m: &WorldReset| { &m.all },
            |m: &mut WorldReset| { &mut m.all },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "time_only",
            |m: &WorldReset| { &m.time_only },
            |m: &mut WorldReset| { &mut m.time_only },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "model_only",
            |m: &WorldReset| { &m.model_only },
            |m: &mut WorldReset| { &mut m.model_only },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<WorldReset>(
            "WorldReset",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for WorldReset {
    const NAME: &'static str = "WorldReset";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.header)?;
                },
                16 => {
                    self.all = is.read_bool()?;
                },
                24 => {
                    self.time_only = is.read_bool()?;
                },
                32 => {
                    self.model_only = is.read_bool()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.header.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if self.all != false {
            my_size += 1 + 1;
        }
        if self.time_only != false {
            my_size += 1 + 1;
        }
        if self.model_only != false {
            my_size += 1 + 1;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.header.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
        }
        if self.all != false {
            os.write_bool(2, self.all)?;
        }
        if self.time_only != false {
            os.write_bool(3, self.time_only)?;
        }
        if self.model_only != false {
            os.write_bool(4, self.model_only)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> WorldReset {
        WorldReset::new()
    }

    fn clear(&mut self) {
        self.header.clear();
        self.all = false;
        self.time_only = false;
        self.model_only = false;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static WorldReset {
        static instance: WorldReset = WorldReset {
            header: ::protobuf::MessageField::none(),
            all: false,
            time_only: false,
            model_only: false,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for WorldReset {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("WorldReset").unwrap()).clone()
    }
}

impl ::std::fmt::Display for WorldReset {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for WorldReset {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x1fignition/msgs/world_reset.proto\x12\rignition.msgs\x1a\x1aignition\
    /msgs/header.proto\"\x89\x01\n\nWorldReset\x12-\n\x06header\x18\x01\x20\
    \x01(\x0b2\x15.ignition.msgs.HeaderR\x06header\x12\x10\n\x03all\x18\x02\
    \x20\x01(\x08R\x03all\x12\x1b\n\ttime_only\x18\x03\x20\x01(\x08R\x08time\
    Only\x12\x1d\n\nmodel_only\x18\x04\x20\x01(\x08R\tmodelOnlyB%\n\x11com.i\
    gnition.msgsB\x10WorldResetProtosb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(1);
            deps.push(super::header::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(WorldReset::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
